analysis_metrics:
  - id: ncloc
    source: Sonar

  - id: new_coverage
    source: Sonar
  
  - id: complexity
    checked: true
    source: Sonar
    complementary: false
    thresholds:
      a:
        lower_bound: 0
        upper_bound: 3
      b:
        lower_bound: 3
        upper_bound: 6
      c:
        lower_bound: 6
        upper_bound: 9
      d:
        lower_bound: 9
        upper_bound: 12
      e:
        lower_bound: 12
        upper_bound: 15  # Upper limit is +15

  - id: cognitive_complexity
    checked: true
    source: Sonar
    complementary: false
    thresholds:
      a:
        lower_bound: 0
        upper_bound: 3
      b:
        lower_bound: 3
        upper_bound: 6
      c:
        lower_bound: 6
        upper_bound: 9
      d:
        lower_bound: 9
        upper_bound: 12
      e:
        lower_bound: 12
        upper_bound: 15  # Upper limit is +15
    
  - id: instability
    checked: true
    source: CodeQL
    complementary: false
    thresholds:
      a:
        lower_bound: 0
        upper_bound: 0.2
      b:
        lower_bound: 0.2
        upper_bound: 0.4
      c:
        lower_bound: 0.4
        upper_bound: 0.6
      d:
        lower_bound: 0.6
        upper_bound: 0.8
      e:
        lower_bound: 0.8
        upper_bound: 1  # Upper limit is 100%

